
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author I M Infas
 */
public class JFrame1 extends javax.swing.JFrame {

    private Connection con = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    
    public JFrame1() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Function to initiate a connection to the database
    private Connection databaseConnection(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/department_db", "root","");
            
            if(con != null){
                System.out.println("Connected to database successfully!");
                return con;
            }else{
                System.out.println("Failed to connect to the database.");
                return null;
            }
        }catch(SQLException ex ){
            JOptionPane.showMessageDialog(null, ex, "SQL connection error!", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    //Load and display data in a table
    public void showData(){
        con = databaseConnection();
        
        try{
          String sql = "SELECT * FROM department";
          pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          
          jTable1.setModel(new DefaultTableModel(null, new String[]{"Dname", "Dnumber", "Mgr_ssn", "Mgr_start_date"}));
          
          while(rs.next()){
              String Dname = rs.getString("Dname");
              String Dnumber = String.valueOf(rs.getInt("Dnumber"));
              String Mgr_ssn = String.valueOf(rs.getInt("Mgr_ssn"));
              String Mgr_start_date = rs.getString("Mgr_start_date");
              
              String data[] = {Dname, Dnumber, Mgr_ssn, Mgr_start_date};
              DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
              tableModel.addRow(data);
          }
          
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex, "Data Loading Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDname = new javax.swing.JTextField();
        txtDnumber = new javax.swing.JTextField();
        txtMgr_ssn = new javax.swing.JTextField();
        txtMgr_start_date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        SwitchTable2 = new javax.swing.JButton();
        SearchUsingDnumber = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dname");

        jLabel2.setText("Dnumber");

        jLabel3.setText("Mgr_ssn");

        jLabel4.setText("Mgr_start_date");

        txtDname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDnameActionPerformed(evt);
            }
        });

        txtDnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDnumberActionPerformed(evt);
            }
        });

        jLabel5.setText("Table 1 - Department");

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        SwitchTable2.setText("Switch to Table 2");
        SwitchTable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchTable2ActionPerformed(evt);
            }
        });

        SearchUsingDnumber.setText("Search using Dnumber");
        SearchUsingDnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUsingDnumberActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dname", "Dnumber", "Mgr_ssn", "Mgr_start_date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Insert)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SwitchTable2)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtMgr_ssn, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                .addComponent(txtDname)
                                                .addComponent(txtDnumber)
                                                .addComponent(txtMgr_start_date))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Delete))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchUsingDnumber)
                        .addGap(58, 58, 58)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SwitchTable2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMgr_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMgr_start_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addGap(18, 18, 18)
                .addComponent(SearchUsingDnumber)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDnumberActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        String Dnumber = txtDnumber.getText();
        
        if(Dnumber.equals("")){
            JOptionPane.showMessageDialog(null,"Dnumber field is required for deleting a data", "Dnumber required!", JOptionPane.ERROR_MESSAGE);
        }else{
            con = databaseConnection();
            
            try{
              String sql = "DELETE FROM department WHERE Dnumber = ?";

              pst = con.prepareStatement(sql);
              pst.setString(1, Dnumber);
              int rowsAffected = pst.executeUpdate();
               
              if(rowsAffected > 0){
                 JOptionPane.showMessageDialog(null, "Data deleted Successfully.");
              }
              
              showData();
              txtDname.setText("");
              txtDnumber.setText("");
              txtMgr_ssn.setText("");
              txtMgr_start_date.setText("");

             }catch(SQLException ex ){
                JOptionPane.showMessageDialog(null, ex);
                showData();
             }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        
        String Dname = txtDname.getText();
        String Dnumber = txtDnumber.getText();
        String Mgr_ssn = txtMgr_ssn.getText();
        String Mgr_start_date = txtMgr_start_date.getText();
 
        if(Dname.equals("") || Dnumber.equals("") || Mgr_ssn.equals("") || Mgr_start_date.equals("")){
            JOptionPane.showMessageDialog(null,"Please fill every field.", "Empty Field(s)!", JOptionPane.ERROR_MESSAGE);
        }else{
            con = databaseConnection();
            jTable1.setModel(new DefaultTableModel(null, new String[]{"Dname", "Dnumber", "Mgr_ssn", "Mgr_start_date"}));
            
            try{
                String sql = "INSERT INTO department" +
                        "(Dname, Dnumber, Mgr_ssn, Mgr_start_date)" + 
                        "VALUES (?,?,?,?)";

                pst = con.prepareStatement(sql); 
                pst.setString(1, Dname);
                pst.setInt(2, Integer.parseInt(Dnumber));
                pst.setInt(3,Integer.parseInt(Mgr_ssn));
                pst.setString(4, Mgr_start_date);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Inserted Successfully.");
                showData();
                   
                txtDname.setText("");
                txtDnumber.setText("");
                txtMgr_ssn.setText("");
                txtMgr_start_date.setText("");
                
            }catch(SQLException ex ){
                JOptionPane.showMessageDialog(null, ex);
                showData();
            }
        }  
    }//GEN-LAST:event_InsertActionPerformed

    
    
    private void SearchUsingDnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUsingDnumberActionPerformed
        String Dnumber = txtDnumber.getText();
        
        if(Dnumber.equals("")){
            JOptionPane.showMessageDialog(null,"Dnumber field is required for searching!", "Field Empty!", JOptionPane.ERROR_MESSAGE);
        }else{
            con = databaseConnection();
            try{
               String sql = "SELECT * FROM department WHERE Dnumber = ?";
               pst = con.prepareCall(sql);
               pst.setString(1, Dnumber);
               rs = pst.executeQuery();
               
               String Dname = "";
               while(rs.next()){
                   
                   Dname = rs.getString("Dname");
                   String Mgr_ssn = rs.getString("Mgr_ssn");
                   String Mgr_start_date = rs.getString("Mgr_start_date");
                   
                   txtDname.setText(Dname);
                   txtMgr_ssn.setText(Mgr_ssn);
                   txtMgr_start_date.setText(Mgr_start_date);
               }
               
               if("".equals(Dname)){
                txtDname.setText("");
                txtMgr_ssn.setText("");
                txtMgr_start_date.setText("");
                
                 JOptionPane.showMessageDialog(null, "No data found!", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex, "Access Error!", JOptionPane.ERROR_MESSAGE);
                showData();
            }
        }
    }//GEN-LAST:event_SearchUsingDnumberActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        String Dname = txtDname.getText();
        String Dnumber = txtDnumber.getText();
        String Mgr_ssn = txtMgr_ssn.getText();
        String Mgr_start_date = txtMgr_start_date.getText();
        
        if(Dname.equals("") || Dnumber.equals("") || Mgr_ssn.equals("") || Mgr_start_date.equals("")){
            JOptionPane.showMessageDialog(null,"Please fill every field to update.", "Empty Field(s)!", JOptionPane.ERROR_MESSAGE);
        }else{
            con = databaseConnection();
            
            try{
                String sql = "UPDATE department SET Dname= ? , Mgr_ssn= ? , Mgr_start_date= ? WHERE Dnumber= ? ";

                pst = con.prepareStatement(sql); 
                pst.setString(1, Dname);
                pst.setInt(2, Integer.parseInt(Mgr_ssn));
                pst.setString(3, Mgr_start_date);
                pst.setInt(4, Integer.parseInt(Dnumber));
                
                

                int rowsEffected = pst.executeUpdate();
                if(rowsEffected > 0){
                   JOptionPane.showMessageDialog(null, "Data updated Successfully.");
                }
                
                showData();
                   
                txtDname.setText("");
                txtDnumber.setText("");
                txtMgr_ssn.setText("");
                txtMgr_start_date.setText("");
                
            }catch(SQLException ex ){
                JOptionPane.showMessageDialog(null, ex);
                showData();
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void SwitchTable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchTable2ActionPerformed
        JFrame2 jf2 = new JFrame2();
        jf2.show();
        dispose();
    }//GEN-LAST:event_SwitchTable2ActionPerformed

    private void txtDnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JButton SearchUsingDnumber;
    private javax.swing.JButton SwitchTable2;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDname;
    private javax.swing.JTextField txtDnumber;
    private javax.swing.JTextField txtMgr_ssn;
    private javax.swing.JTextField txtMgr_start_date;
    // End of variables declaration//GEN-END:variables
}
