
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author I M Infas
 */
public class JFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame2
     */
    
    private Connection con = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    
    public JFrame2() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Function to initiate a connection to the database
    private Connection databaseConnection(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/department_db", "root","");
            
            if(con != null){
                System.out.println("Connected to database successfully!");
                return con;
            }else{
                System.out.println("Failed to connect to the database.");
                return null;
            }
        }catch(SQLException ex ){
            JOptionPane.showMessageDialog(null, ex, "SQL connection error!", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    //Load and display data in a table
    public void showData(){
        con = databaseConnection();
        
        try{
          String sql = "SELECT * FROM dept_locations";
          pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          
          jTable2.setModel(new DefaultTableModel(null, new String[]{"Dnumber", "Dlocation"}));
          
          while(rs.next()){
              String Dnumber = String.valueOf(rs.getInt("Dnumber"));
              String Dlocation = rs.getString("Dlocation");
              
              String data[] = {Dnumber, Dlocation};
              DefaultTableModel tableModel = (DefaultTableModel)jTable2.getModel();
              tableModel.addRow(data);
          }
          
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex, "Data Loading Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDnumber = new javax.swing.JTextField();
        txtDlocation = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        SwitchTable1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtNewDlocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Table 2 - Dept_locations");

        jLabel2.setText("Dnumber");

        jLabel3.setText("Dlocation");

        txtDnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDnumberActionPerformed(evt);
            }
        });

        txtDlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDlocationActionPerformed(evt);
            }
        });

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        SwitchTable1.setText("Switch to Table 1");
        SwitchTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchTable1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dnumber", "Dlocation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        txtNewDlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewDlocationActionPerformed(evt);
            }
        });

        jLabel4.setText("New");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(SwitchTable1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Insert)
                                .addGap(18, 18, 18)
                                .addComponent(Update)
                                .addGap(18, 18, 18)
                                .addComponent(Delete)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDlocation, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtDnumber))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNewDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(SwitchTable1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Insert)
                            .addComponent(Update)
                            .addComponent(Delete))
                        .addGap(89, 89, 89))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDnumberActionPerformed

    private void txtDlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDlocationActionPerformed

    
    
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

        String Dnumber = txtDnumber.getText();
        String Dlocation = txtDlocation.getText();
        String newDlocation = txtNewDlocation.getText();
              
        if(Dnumber.equals("") || Dlocation.equals("") || newDlocation.equals("")){
            JOptionPane.showMessageDialog(null,"Please fill every field to update.", "Empty Field(s)!", JOptionPane.ERROR_MESSAGE);
            if(newDlocation.equals("")){
                JOptionPane.showMessageDialog(null,"Please add new location to update", "Add new location", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            con = databaseConnection();
            
            try{
                String sql = "UPDATE dept_locations SET Dnumber= ? , Dlocation= ?  WHERE Dnumber= ? AND Dlocation= ?";

                pst = con.prepareStatement(sql); 
               
                pst.setInt(1, Integer.parseInt(Dnumber));
                pst.setString(2, newDlocation);
                pst.setInt(3, Integer.parseInt(Dnumber));
                pst.setString(4, Dlocation);

                int rowsEffected = pst.executeUpdate();
                if(rowsEffected > 0){
                   JOptionPane.showMessageDialog(null, "Data updated Successfully.");
                }
                
                showData();

                txtDnumber.setText("");
                txtDlocation.setText("");
                txtNewDlocation.setText("");

            }catch(SQLException ex ){
                JOptionPane.showMessageDialog(null, ex);
                showData();
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void SwitchTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchTable1ActionPerformed
       JFrame1 jf1 = new JFrame1();
       jf1.show();
        
       dispose();
    }//GEN-LAST:event_SwitchTable1ActionPerformed

    
    
    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        
        String Dnumber = txtDnumber.getText();
        String Dlocation = txtDlocation.getText();
 
        if(Dnumber.equals("") || Dlocation.equals("")){
            JOptionPane.showMessageDialog(null,"Please fill every field.", "Empty Field(s)!", JOptionPane.ERROR_MESSAGE);
        }else{
            con = databaseConnection();
            jTable2.setModel(new DefaultTableModel(null, new String[]{"Dnumber", "Dlocation"}));
            
            try{
                String sql = "INSERT INTO dept_locations" +
                        "(Dnumber, Dlocation)" + 
                        "VALUES (?,?)";

                pst = con.prepareStatement(sql); 
           
                pst.setInt(1, Integer.parseInt(Dnumber));
                pst.setString(2, Dlocation);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Inserted Successfully.");
                showData();
   
                txtDnumber.setText("");
                txtDlocation.setText("");
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
                showData();
            }
        }
    }//GEN-LAST:event_InsertActionPerformed

    
    
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       String Dnumber = txtDnumber.getText();
       String Dlocation = txtDlocation.getText();
        
        if(Dnumber.equals("") || Dlocation.equals("")){
            JOptionPane.showMessageDialog(null,"Dnumber and Dlocation fields are required for deleting a data", "Fill required fields!", JOptionPane.ERROR_MESSAGE);
        }else{
            con = databaseConnection();
            
            try{
              String sql = "DELETE FROM dept_locations WHERE Dnumber = ? AND Dlocation = ?";

              pst = con.prepareStatement(sql);
              pst.setInt(1, Integer.parseInt(Dnumber));
              pst.setString(2, Dlocation);
              
              int rowsAffected = pst.executeUpdate();
               
              if(rowsAffected > 0){
                 JOptionPane.showMessageDialog(null, "Data deleted Successfully.");
              }
              
              showData();
         
              txtDnumber.setText("");
              txtDlocation.setText("");

             }catch(SQLException ex ){
                JOptionPane.showMessageDialog(null, ex);
                showData();
             }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void txtNewDlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewDlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewDlocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JButton SwitchTable1;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtDlocation;
    private javax.swing.JTextField txtDnumber;
    private javax.swing.JTextField txtNewDlocation;
    // End of variables declaration//GEN-END:variables
}
